#!/usr/bin/env bash
# Configures an Ubuntu server with these requirements: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8

sed -i '/^127\.0\.0\.1.*localhost/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts

sed -i '/facebook\.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
