#!/usr/bin/env bash
# Configures an Ubuntu server with these requirements: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8

# Check and replace localhost entry
if grep -q "localhost" /etc/hosts; then
	# Remove localhost entry
    grep -v "localhost" /etc/hosts | sudo tee /tmp/hosts > /dev/null
	# Add new localhost entry
    echo "127.0.0.2 localhost" | sudo tee -a /tmp/hosts > /dev/null
	# Replace original file
    sudo cp /tmp/hosts /etc/hosts
else
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
fi

# Check and replace facebook.com entry
if grep -q "facebook.com" /etc/hosts; then
	# Remove facebook entry
    grep -v "facebook.com" /etc/hosts | sudo tee /tmp/hosts > /dev/null
	# Add new facebook entry
    echo "8.8.8.8 facebook.com" | sudo tee -a /tmp/hosts > /dev/null
	# Replace original file
    sudo cp /tmp/hosts /etc/hosts
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
